// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

type Device struct {
	ID       string
	Name     string
	Location string
	Token    string
}

type SensorDatum struct {
	ID          string
	SensorID    string
	Temperature float64
	Humidity    float64
	Timestamp   string
}
