// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package repository

import (
	"context"
)

const getDevices = `-- name: GetDevices :many
SELECT id, name, location, token FROM devices
ORDER BY name
`

func (q *Queries) GetDevices(ctx context.Context) ([]Device, error) {
	rows, err := q.db.QueryContext(ctx, getDevices)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Device
	for rows.Next() {
		var i Device
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Location,
			&i.Token,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSensorDataByTime = `-- name: GetSensorDataByTime :many
SELECT id, sensor_id, temperature, humidity, timestamp FROM sensor_data s
WHERE s.sensor_id = ?
and s.timestamp >= ?
and s.timestamp < ?
`

type GetSensorDataByTimeParams struct {
	SensorID    string
	Timestamp   string
	Timestamp_2 string
}

func (q *Queries) GetSensorDataByTime(ctx context.Context, arg GetSensorDataByTimeParams) ([]SensorDatum, error) {
	rows, err := q.db.QueryContext(ctx, getSensorDataByTime, arg.SensorID, arg.Timestamp, arg.Timestamp_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SensorDatum
	for rows.Next() {
		var i SensorDatum
		if err := rows.Scan(
			&i.ID,
			&i.SensorID,
			&i.Temperature,
			&i.Humidity,
			&i.Timestamp,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertDevice = `-- name: InsertDevice :exec
INSERT INTO devices (id, name, location, token)
VALUES (?, ?, ?, ?)
`

type InsertDeviceParams struct {
	ID       string
	Name     string
	Location string
	Token    string
}

func (q *Queries) InsertDevice(ctx context.Context, arg InsertDeviceParams) error {
	_, err := q.db.ExecContext(ctx, insertDevice,
		arg.ID,
		arg.Name,
		arg.Location,
		arg.Token,
	)
	return err
}

const insertSensorData = `-- name: InsertSensorData :one
INSERT INTO sensor_data (id, sensor_id, temperature, humidity, timestamp)
VALUES (?, ?, ?, ?, ?)
RETURNING id, sensor_id, temperature, humidity, timestamp
`

type InsertSensorDataParams struct {
	ID          string
	SensorID    string
	Temperature float64
	Humidity    float64
	Timestamp   string
}

func (q *Queries) InsertSensorData(ctx context.Context, arg InsertSensorDataParams) (SensorDatum, error) {
	row := q.db.QueryRowContext(ctx, insertSensorData,
		arg.ID,
		arg.SensorID,
		arg.Temperature,
		arg.Humidity,
		arg.Timestamp,
	)
	var i SensorDatum
	err := row.Scan(
		&i.ID,
		&i.SensorID,
		&i.Temperature,
		&i.Humidity,
		&i.Timestamp,
	)
	return i, err
}
