// Package rest provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package rest

import (
	"time"
)

const (
	TokenAuthScopes = "TokenAuth.Scopes"
)

// Sensor defines model for Sensor.
type Sensor struct {
	Id       string `json:"id"`
	Location string `json:"location"`
	Name     string `json:"name"`
	Token    string `json:"token"`
}

// SensorData defines model for SensorData.
type SensorData struct {
	Humidity    float32   `json:"humidity"`
	SensorId    string    `json:"sensorId"`
	Temperature float32   `json:"temperature"`
	Timestamp   time.Time `json:"timestamp"`
}

// GetDataSearchParams defines parameters for GetDataSearch.
type GetDataSearchParams struct {
	// From Начало диапазона (ISO 8601)
	From time.Time `form:"from" json:"from"`

	// To Конец диапазона (ISO 8601)
	To time.Time `form:"to" json:"to"`
}

// PostSendJSONBody defines parameters for PostSend.
type PostSendJSONBody struct {
	Humidity    float32 `json:"humidity"`
	Temperature float32 `json:"temperature"`
}

// PostSendJSONRequestBody defines body for PostSend for application/json ContentType.
type PostSendJSONRequestBody PostSendJSONBody
